### ISSUE TITLE
Implement command line parsing

### ISSUE THREAD

**Issue by dolftax** [dolftax/mikasa#1]
Usage: mikasa [options] ws://hostname

  Options:

    -h, --help                      output usage information
    -A, --amount <connections>      the amount of persistent connections to generate
    -C, --concurrent <connections>  how many concurrent-connections per second
    -M, --messages <messages>       messages to be send per connection
    -W, --workers <cpus>            workers to be spawned

**Comment by dolftax** [comment]
@hTrap @AkhilHector Interested to take this?

**Comment by AkhilHector** [comment]
sure on it

**Comment by dolftax** [comment]
@AkhilHector Use Go's native command line parser.

**Comment by dolftax** [comment]
Well, Because of `https://github.com/isaacs/github/issues/100` // I can't assign the issues to you guys. So, feel free to fork and send a PR to master.

**Comment by AkhilHector** [comment]
Cool man not an issue !!

**Comment by dolftax** [comment]
@AkhilHector I am planning to work on this now. Any progress?

**Comment by dolftax** [comment]
Ref - https://github.com/dolftax/mikasa/commit/c59d7b83c7ec29c4a9896e08efc7a09bf9d64116
